### ISSUE TITLE
optparser problem

### ISSUE THREAD

**Issue by jcgrenier** [sahwa/sourcefindV2#1]
Hello! I tried the sourcefindV2 R script but wasn't able to make it work with the latest version using R 4.1.0. I needed to go back to the earlier version. Would it be possible to solve this issue? It seems to come from the optparser package.

Thanks a lot!

**Comment by sahwa** [comment]
Hi,

Sorry about that - I updated the way the arguments were parsed and didn't update the manual. I will update it today and it should clarify how the arguments are given. The core algorithm and files required has stayed the same so it will be consistent with any previous versions you have used.

Best,

Sam

**Comment by jcgrenier** [comment]
Alright! Thanks a lot for the quick reply and for the quick fix in the doc! 

Best,
JC

**Comment by sahwa** [comment]
I've now updated it slightly. There are a couple of options for you. 

You could keep the same parameter file which specifies all the arguments and run as follows ``Rscript sourcefindv2.R -p your_paramfile.txt``. The other option is to specify any of the copyvectors, targets, output file name or idfile using command line arguments, which you can see by running ``Rscript sourcefindv2.R --help``. There is a small example bash script in the examples directory which shows you how to do this. 

You must specify the ``-p`` flag on the command line and if you leave the other flags blank, it will default to the values in the parameter file. I'll update the manual when I get my hands on the .tex file.

Could you try and see if it works and let me know if you have any issues. I've tested it myself and it seems to work, but it's been a while since I've looked at this!

Best,

Sam

**Comment by jcgrenier** [comment]
Thanks a lot, it seems to work! 
Have a nice day!!

JC
